id: ad65a97582364558b5704463d3c70032
initial_creation_type: ocr
source_metadata:
  volumes:
    1531971339db4e3f98d42bd109eda10f:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: དཔལ་གསང་བ་འདུས་པའི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1634
      volume_number: 18
